# Site settings

title: Jean Laurent | Portfolio
url: "https://jeanlrnt.github.io/Portfolio_FR"
icon: "images/jeanlaurent.png"
baseurl: ""
bio-page-label: CV
theme-home: theme-home-page.html
theme-projects: theme-projects-page.html
theme-essays: theme-essays-page.html
theme-bio: theme-bio-page.html

markdown: kramdown
include: [_data]
