# Site settings

title: Jean Laurent | Portfolio
url: "https://www.jeanlaurent.fr"
baseurl: ""
icon: "favicon.ico"
bio-page-label: CV
projects-page-label: Projets
essays-page-label: Publications
home-page-label: Accueil
skills: Aptitudes
activities: Bénévolat
interests: Interêts
publications: Publications
awards: Recompenses
references: Références
education: Scolarité
work: Experience
more: "Voir Plus"
theme-home: theme-home-page.html
theme-projects: theme-projects-page.html
theme-essays: theme-essays-page.html
theme-bio: theme-bio-page.html

markdown: kramdown
include: [_data]
